apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: traefik
data:
  traefik-config.yaml: |
    http:
      middlewares:
        headers-default:
          headers:
            frameDeny: true
            sslRedirect: true
            browserXssFilter: true
            contentTypeNosniff: true
            #HSTS
            stsIncludeSubdomains: true
            forceSTSHeader: true
            stsPreload: true
            stsSeconds: 31536000
              #customFrameOptionsValue: SAMEORIGIN
