apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: dns01-letsencrypt-staging
  namespace: cert-manager
spec:
  acme:
    # Email address used for ACME registration
    email: infra@linkurio.us
    # The ACME server URL
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: dns01-letsencrypt-staging
    solvers:
    - dns01:
        webhook:
          groupName: acme.bwolf.me
          solverName: gandi
          config:
            apiKeySecretRef:
              key: api-token
              name: gandi-credentials
